In [ ]:
"""
118. Pascal's Triangle
Given a non-negative integer numRows, generate the first numRows of Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it.

Example:
Input: 5
Output:
[
     [1],
    [1,1],
   [1,2,1],
  [1,3,3,1],
 [1,4,6,4,1]
]
"""
class Solution:
    def generate(self, numRows):
        
        result = []         
        
        prev = []
        
        for i in range(numRows):
            temp = [1]*(i+1)

            for j in range(1, i):
                temp[j] = prev[j-1]+prev[j]
            prev = temp
            
            result.append(temp[:])
        
        return result 

---

In [ ]:
"""
119. Pascal's Triangle II

Given a non-negative index k where k ≤ 33, return the kth index row of the Pascal's triangle.

Note that the row index starts from 0.
In Pascal's triangle, each number is the sum of the two numbers directly above it.

Example:

Input: 3
Output: [1,3,3,1]
"""
class Solution:
    def getRow(self, rowIndex):
                
        result = []
        prev = []
        
        for i in range(rowIndex+1):
            
            result = [1]*(i+1)
            
            for j in range(1, i):
                result[j]  = prev[j-1]+prev[j]
            prev = result 
        
        return result 
            

---

In [61]:
'''
Write a function to display the power set of a set of integers;
e.g. set={1,2}, powerSet = {{},{1},{2},{1,2}}
'''
def power_set_2(set_):
    subsets = [[]] 
    for element in set_:
        for ind in range(len(subsets)): 
            subsets.append(subsets[ind] + [element]) 
    return subsets

In [62]:
#Example 1
data = {1, 2}
power_set_2(data)

[[], [1], [2], [1, 2]]

In [63]:
#Example 2
data = [{},{1},{2},{1,2}]
power_set_2(data)

[[],
 [{}],
 [{1}],
 [{}, {1}],
 [{2}],
 [{}, {2}],
 [{1}, {2}],
 [{}, {1}, {2}],
 [{1, 2}],
 [{}, {1, 2}],
 [{1}, {1, 2}],
 [{}, {1}, {1, 2}],
 [{2}, {1, 2}],
 [{}, {2}, {1, 2}],
 [{1}, {2}, {1, 2}],
 [{}, {1}, {2}, {1, 2}]]

---

In [69]:
"""
54. Spiral Matrix
Given a matrix of m x n elements (m rows, n columns), return all elements of the matrix in spiral order.

Example 1:

Input:
[
 [ 1, 2, 3 ],
 [ 4, 5, 6 ],
 [ 7, 8, 9 ]
]
Output: [1,2,3,6,9,8,7,4,5]
Example 2:

Input:
[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9,10,11,12]
]
Output: [1,2,3,4,8,12,11,10,9,5,6,7]
"""

def spiralOrder(matrix):
    
    if not matrix:
        return []
    
    r_start, c_start = 0, 0
    r_end, c_end = len(matrix)-1, len(matrix[0])-1
    result = []
    size = len(matrix)*len(matrix[0])
    
    while len(result)<size:
                
        result.extend(matrix[r_start][c_start:c_end+1])
        
        for i in reversed(range(r_start+1, r_end)):
            result.append(matrix[i][c_end])
            
        if r_end>r_start:
            result.extend(matrix[r_end][c_start:c_end+1][::-1])
        
        if c_start<c_end:
            for j in reversed(range(r_start+1, r_end)):
                result.append(matrix[j][c_start])
        
        r_start+=1; c_end-=1; r_end-=1; c_start+=1
    return result

    """
    def spiralOrder(matrix):
    
    if not matrix:
        return []
    rows = len(matrix)
    cols = len(matrix[0])
    
    visited = {(i, j):False for i in range (rows) for j in range(cols)}
    result = []
    
    directions = [[0, 1], [1, 0], [0, -1], [-1, 0]]
    
    size = rows*cols
    
    index =0
    x, y = 0, 0
    result.append(matrix[0][0])
    visited[(0, 0)] = True
    
    while len(result)< size:
        
        h = x+directions[index][0]
        v = y+directions[index][1]
                                        
        if h>=0 and h<rows and v>=0 and v<cols and not visited[(h, v)]: 
            x = h
            y = v
            visited[(x, y)] = True
        else:
            index+=1
            if index==4:
                index = 0
            continue
        
        result.append(matrix[x][y])

    
    return result 
    """    

In [70]:
#Example 1
matrix = [
 [ 1, 2, 3 ],
 [ 4, 5, 6 ],
 [ 7, 8, 9 ]
]
spiralOrder(matrix)

[1, 2, 3, 6, 9, 8, 7, 4, 5]

In [71]:
#Example 2
matrix =[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9,10,11,12]
]
spiralOrder(matrix)

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]

---

In [78]:
"""
Find triplets. 

"""
def findTriplets(arr):
    
    arr.sort()
    
    results = []
    global counter
    counter=0
    def backtracking(nums, remainder, solset):
        global counter
        if not nums:
            return
        counter+=1
        for j, d in enumerate(nums):
            
            if d>0 and d>remainder: #bounding condition 1
                return
            
            if len(solset)>2: # bounding condition 2
                return 
            elif d==remainder and len(solset)==2:
                results.append(solset+[d])
                return 
            
            backtracking(nums[j+1:], remainder-d, solset+[d])
        
                                                          
            
    for i, n in enumerate(arr):
        if i>0 and arr[i-1]==n:
            continue
        arg = arr[:]
        arg.remove(n)
        backtracking(arg, n, [n])
        
    print(counter)

    return results
        

def findTriplets2(arr):
    
    arr.sort()
    
    results = []
    global counter
    counter=0
    def helper(nums, target):
        global counter
        counter+=1
        left = 0
        right = len(nums)-1
        while right>left:
            
            if left>0 and nums[left-1]==nums[left]:
                left+=1
                continue
            if right+1<len(nums) and nums[right]==nums[right+1]:
                right-=1
                continue
                
            if nums[left]+nums[right]>target:
                right-=1
            elif nums[left]+nums[right]<target:
                left+=1
            else:
                results.append([nums[left], nums[right], target]) 
                left+=1
                right-=1
                                                          
            
    for i, n in enumerate(arr):
        if i>0 and arr[i-1]==n:
            continue
        arg = arr[:]
        arg.remove(n)
        helper(arg, n)
        
    print(counter)

    return results
        

In [79]:
test_case = [-3, -2, -2, -2, -1, -1, 0, 1, 2, 3]

In [80]:
findTriplets(test_case)

187


[[-3, -2, -1],
 [-3, -2, -1],
 [-3, -2, -1],
 [-2, -3, 1],
 [-2, -2, 0],
 [-2, -2, 0],
 [-2, -1, -1],
 [-1, -3, 2],
 [-1, -2, 1],
 [-1, -2, 1],
 [-1, -2, 1],
 [-1, -1, 0],
 [0, -3, 3],
 [0, -2, 2],
 [0, -2, 2],
 [0, -2, 2],
 [0, -1, 1],
 [0, -1, 1],
 [1, -2, 3],
 [1, -2, 3],
 [1, -2, 3],
 [1, -1, 2],
 [1, -1, 2],
 [2, -1, 3],
 [2, -1, 3],
 [3, 1, 2]]

In [81]:
findTriplets2(test_case)

7


[[-2, -1, -3],
 [-3, 1, -2],
 [-2, 0, -2],
 [-1, -1, -2],
 [-3, 2, -1],
 [-2, 1, -1],
 [-1, 0, -1],
 [-3, 3, 0],
 [-2, 2, 0],
 [-1, 1, 0],
 [-2, 3, 1],
 [-1, 2, 1],
 [-1, 3, 2],
 [1, 2, 3]]

---

In [82]:
from collections import defaultdict

"""
Find rectangle with biggest sum:
e.g.

[
 [-2, -5, -9, 2],
 [-2, -5, 2, -7],
 [3, 2, -10, -13],
 [8, 30, -1, -2]
]

[
 [3, 2], 
 [8, 30]
]
"""

def printSubmatrix(matrix, lookup):
    
    max_sum = max(lookup)
    solset = lookup[max_sum]
    print("The max sum is: ", max_sum)
    print("The submatrix(s): ")

    for k, d in enumerate(solset):
        a,b,c,d = d[0][0],d[0][1],d[1][0],d[1][1]
        ans = []

        for i in range(a, c):
            temp=[]
            for j in range(b, d):
                temp.append(matrix[i][j])
            ans.append(temp)
        print("Solution:", k+1)
        print(np.matrix(ans))
        
def biggestSum(matrix):
    
    if not matrix:
        return 0
    
    rows = len(matrix)
    cols = len(matrix[0])
    
    lookup = defaultdict(list)
    
    for i in range(rows):
        for j in range(cols):
                
            # add all row matrix
            for k in range(j+1, cols+1):                
                for c in range(i+1):
                    elem3 = sum(sum(matrix[v][j:k]) for v in range(c, i+1))
                    lookup[elem3].append([[c, j], [i+1, k]])
    
    printSubmatrix(matrix, lookup)   
    return lookup


In [83]:
import numpy as np
matrix1 = [[-2, -5, -9, 2], [-2, -5, 2, -7], [3, 2, -10, -13], [8, 30, -1, -2]]
print(np.matrix(matrix1))

[[ -2  -5  -9   2]
 [ -2  -5   2  -7]
 [  3   2 -10 -13]
 [  8  30  -1  -2]]


In [84]:
matrix2 = [[-2, -5], [-2, -5]]
print(np.matrix(matrix2))
biggestSum(matrix2)

[[-2 -5]
 [-2 -5]]
The max sum is:  -2
The submatrix(s): 
Solution: 1
[[-2]]
Solution: 2
[[-2]]


defaultdict(list,
            {-2: [[[0, 0], [1, 1]], [[1, 0], [2, 1]]],
             -7: [[[0, 0], [1, 2]], [[1, 0], [2, 2]]],
             -5: [[[0, 1], [1, 2]], [[1, 1], [2, 2]]],
             -4: [[[0, 0], [2, 1]]],
             -14: [[[0, 0], [2, 2]]],
             -10: [[[0, 1], [2, 2]]]})

---