In [11]:
# Find all paths from a given source to destination using depth first search
from collections import defaultdict
class Graph:
    def __init__(self, vertices):
        self.v = vertices
        self.graph = defaultdict(list)
        
    def addEdge(self, u, v):
        self.graph[u].append(v)
    
    def printAllPathsUtil(self, u, v, visited, path, all_paths):
        
        visited[u] = True
        path.append(u)
        
        if u==d:
            all_paths.append(path[:])
        else:
            for i in self.graph[u]:
                if visited[i]==False:
                    self.printAllPathsUtil(i, d, visited, path, all_paths)
        path.pop()
        visited[u] = False
        
    def printAllPaths(self, s, d):
        visited = [False]*(self.v)
        path = []
        all_paths =[]
        self.printAllPathsUtil(s, d, visited, path, all_paths)
        return all_paths

g = Graph(4)
g.addEdge(0, 1)
g.addEdge(0, 2)
g.addEdge(0, 3)
g.addEdge(2, 0)
g.addEdge(2, 1)
g.addEdge(1, 3)
s = 2 ;d = 3
print("Folllowing are all different paths from %d to %d : "%(s, d))
g.printAllPaths(s, d)

Folllowing are all different paths from 2 to 3 : 


[[2, 0, 1, 3], [2, 0, 3], [2, 1, 3]]

---

In [16]:
"""
Finding degree and degree sequence of a given graph
"""
class Graph(object):
    def __init__(self, graph_dict=None):
        if(graph_dict==None):
            graph_dict = {}
        self.__graph_dict = graph_dict
    def vertices(self):
        return self.__graph_dict.keys()
        
    def edges(self):
        edges =[]
        for node in self.__graph_dict:
            
            for adj in self.__graph_dict[node]:
                if({node, adj} not in edges):
                    edges.append({node, adj})
                    
        return edges
        
    def add_vertex(self, vertex):
        self.__graph_dict[vertex] = []
        
    def add_edge(self, edge):
        (v1, v2) = tuple(edge)
        if(v1 in self.__graph_dict.keys()):
            self.__graph_dict[v1].append(v2)
        else:
            slef.__graph_dict[v1]=[v2]
            
    def degree(self, vertex):
        result = self.__graph_dict[vertex]
        return len(result)+ result.count(vertex)
    
    def degree_sequence(self):
        seq =[]
        
        for vertex in self.vertices():
            seq.append(self.degree(vertex))
        
        return tuple(sorted(seq, reverse=True))

In [17]:
g = { "a" : ["d", "f"],
      "b" : ["c"],
      "c" : ["b","c", "d", "e"],
      "d" : ["a", "c"],
      "e" : ["c"],
      "f" : ["d", "a"]
        }
graph = Graph(g)

In [18]:
# Find the degree of node 'c'
graph.degree("c")

5

In [19]:
# Find the degree sequence of the graph
graph.degree_sequence()

(5, 2, 2, 2, 1, 1)

---

In [35]:
"""
Methods to check if a graph is connected and also finding diameter of a graph. 

Note that, below, a very simple method is used to check if a given graph is connected and it is not optimal. 
"""
class Graph(object):
    def __init__(self, graph_dict=None):
        if(graph_dict==None):
            graph_dict = {}
        self.__graph_dict = graph_dict
    def vertices(self):
        return self.__graph_dict.keys()
    
    def is_connected(self, vertices_encountered=None, start_vertex=None):
        
        if(vertices_encountered is None):
            vertices_encountered = set()
        
        gdict = self.__graph_dict
        vertices = list(gdict.keys()) # don't forget the list casting here
        
        if not start_vertex:
            start_vertex = vertices[0]
        
        vertices_encountered.add(start_vertex)
        
        if(len(vertices_encountered)!=len(vertices)):
            for vertex in gdict[start_vertex]:
                if(vertex not in vertices_encountered):
                    if self.is_connected(vertices_encountered, vertex):
                        return True
        else:
            return True
        
        return False
    
    def diameter(self):
        
        v = list(self.vertices())
        
        pairs = [[v[i], v[j]] for i in range(len(v)-1) for j in range(i+1, len(v))]
        
        smallest =[]
        
        for i, j in pairs:
            all_paths = self.find_all_paths_best(i, j)
            smallest.append(sorted(all_paths, key=len)[0])
        
        smallest.sort(key=len)
        return len(smallest[-1])-1
    
    def find_all_paths_best(self, start_vertex, end_vertex):
        
        all_paths =[]
        
        vertices = self.vertices()
        
        visited = {vertice:False for vertice in vertices}
        
        self.helper(start_vertex, end_vertex, all_paths, [], visited)
        
        return all_paths
    
    def helper(self, start_vertex, end_vertex, all_paths, path, visited):
        

        if(start_vertex not in self.__graph_dict):
            return 
        
        
        if (start_vertex==end_vertex):
            all_paths.append(path+[start_vertex])
            return
        
        if visited[start_vertex]:
            return 
        
        path.append(start_vertex)
        visited[start_vertex] = True

        for vertex in self.__graph_dict[start_vertex]:
            self.helper(vertex, end_vertex, all_paths, path, visited)
        
        path.pop()
        visited[start_vertex] = False
        return 
            

In [36]:
g = { "a" : ["c"],
      "b" : ["c","e","f"],
      "c" : ["a","b","d","e"],
      "d" : ["c"],
      "e" : ["b","c","f"],
      "f" : ["b","e"]
}
graph = Graph(g)

In [37]:
#check if a graph is connected
graph.is_connected()

True

In [38]:
# Find diameter of a graph
graph.diameter()

3

---

In [43]:
"""
Find articulation points in a graph using a slightly modified version of Tarjan Algorithm.

"""

from collections import defaultdict

def articulationPoint(n, connections):
    '''
    1) build the graph
    2) use Tarjan Algorithm (slightly modified dfs) to find critical nodes
       - low-link
       - discovery time (counter)
       - parent
    '''
    graph = defaultdict(list)
    
    for i, j in connections:
        graph[i].append(j)
        graph[j].append(i)
    
    low=[0]*n
    parent = [-1]*n
    disc = [0]*n
    results =set()
    
    def Tarjan(steps, curr, prev):
        low[curr] = steps
        disc[curr] = steps
        child_count =0
        for adj in graph[curr]:
            if adj ==prev: continue
            
            
            if not low[curr]:
                child_count+=1
                parent[adj] = curr
                Tarjan(steps+1, adj, curr)
                
                low[curr] = min(low[adj], low[curr])
                
                if parent[curr]!=-1 and low[adj]>=steps:
                    results.add(curr)
                
                if parent[curr]==-1 and child_count>1:
                    results.add(curr)
            
            elif (adj!=parent[prev]):
                
                low[curr] = min(low[curr], disc[adj])
    
    Tarjan(1, 0, -1)
    
    return list(results)
    

In [44]:
#Example 
#n = 7
n=5
#connections = [[0, 1], [0, 2], [1, 3], [2, 3], [2, 5], [5, 6], [3, 4]]
connections = [[0,1],[1,2],[2,0],[3,0],[3,4],[4,0]]
articulationPoint(n, connections)

[0]

---

In [45]:
"""
Find critical connections using depth first search or Tarjan Algorithm to find all the critical connections
"""
from collections import defaultdict
class Solution:
    def criticalConnections(self, n: int, connections):
        '''
        1) build a graph 
        2) use a slightly modified version of depth first search or
        Tarjan Algorithm to find all the critical connections
        '''
        
        graph = defaultdict(list)
        
        for i, j in connections:
            graph[i].append(j)
            graph[j].append(i)
        
        results =[]
        low= [0]*n
        
        def dfs(node, parent, steps):
            
            low[node] = steps
            
            for adj in graph[node]:
                
                if adj==parent: continue # cycle detection
                
                if not low[adj]:
                    dfs(adj, node, steps+1)
                    
                
                low[node] = min(low[node], low[adj])
                
                if low[adj]>steps:
                    results.append([node, adj])
                    
        
        
        dfs(0, -1, 1)
        
        return results

In [46]:
n = 7
#n=5
connections = [[0, 1], [0, 2], [1, 3], [2, 3], [2, 5], [5, 6], [3, 4]]
#connections = [[0,1],[1,2],[2,0],[3,0],[3,4],[4,0]]
obj = Solution()
obj.criticalConnections(n, connections)

[[5, 6], [2, 5], [3, 4]]

---

In [87]:
"""
Find cycles in a directed graph.

"""

from collections import defaultdict, deque 

class Graph:
    def __init__(self):
        self.g = defaultdict(list)
    
    def insertEdge(self, s, d):
        self.g[s].append(d)
        if d not in self.g:
            self.g[d]
        
    def vertices(self):
        return list(self.g.keys())
    
    def isThereACycle(self):
        visited = ["White"]*(len(self.g))
        
        def helper(s):
            
            visited[s] = "Gray"
            for v in self.g[s]:
                if visited[v]=="Gray":
                    return True
                if visited[v]=="White":
                    if helper(v):
                        return True
            
            visited[s] = "Black"
            
            return False
        
        for v in range(len(self.g)):
            if visited[v]=="White":
                if helper(v):
                    return True
                
        return False
                

    def findCyclesDirected(self):
        color = ["White"]*(len(self.g))
        cycles = []
        
        def helper(s, path):
            
            color[s] = "Gray"
            for v in self.g[s]:
                if color[v]=="Gray":
                    idx = path.index(v)
                    cycles.append(path[idx:]+[v])
                if color[v]=="White":
                    helper(v, path+[v])
            
            color[s] = "Black"

        for v in range(len(self.g)):
            if color[v]=="White":
                helper(v, [v]) 
                
        return cycles
        
    def buildGraph(self, edges):
        for edge in edges:
            self.insertEdge(edge[0], edge[1])     
        

In [88]:
g = [[0, 1], [1, 2], [3, 1], [2, 3], [3, 3]]
obj = Graph()
obj.buildGraph(g)
obj.isThereACycle()

True

In [89]:
obj.findCyclesDirected()

[[1, 2, 3, 1], [3, 3]]

---

In [91]:
"""
Find cycles in an undirected graph.

"""

from collections import defaultdict, deque 

class Graph:
    def __init__(self):
        self.g = defaultdict(list)
    
    def insertEdge(self, s, d):
        if s==d: # Need this incase of self-loop
            self.g[s].append(d)
            return 
        self.g[s].append(d)
        self.g[d].append(s)
      
    def findCyclesUndirected(self):
        color = ["White"]*(len(self.g))
        cycles = []
        
        def helper(s, path, parent):
            
            color[s] = "Gray"
            for v in self.g[s]:
                if color[v]=="White":
                    helper(v, path+[v], s)
                    
                if color[v]=="Gray" and v!=parent:
                    idx = path.index(v)
                    cycles.append(path[idx:]+[v])
                    
            color[s] = "Black"
            
        for v in range(len(self.g)):
            if color[v]=="White":
                helper(v, [v], v) 
            
        print(cycles)        
        
    def buildGraph(self, edges):
        for edge in edges:
            self.insertEdge(edge[0], edge[1])     
        

In [92]:
g = [[0, 1], [1, 2], [3, 1], [2, 3], [3, 3]]
obj = Graph()
obj.buildGraph(g)
obj.findCyclesUndirected()

[[1, 2, 3, 1], [3, 3]]


In [47]:

"""
The 'permute' function given below uses depth first search to find 
all permutations of a given list of integers/strings.

e.g. Input: [1,2,3] 
Output:[ [1,2,3], [1,3,2], [2,1,3], [2,3,1], [3,1,2], [3,2,1]]
"""

class Solution:
    
    def __init__(self):
        self.valid = []
    
    def permute(self, G):
        
        n = len(G)
        
        def dfs(G, s, visited, path, path_len):
            #print("path_len: ", path_len, " n:", n, path, " Visisted: ", visited)
            if path_len == n - 1:
                self.valid.append(path + [s])
                return
            for neigh in G:
                if s != neigh and neigh not in visited:
                    dfs(G, neigh, visited + [s], path + [s], path_len + 1)
                    
        for v in G:
            dfs(G, v, [], [], 0)
            
        return self.valid
    
    #Alternative solutions without using Depth First Search.
    """
    import itertools

    class Solution:

        def permute(self, G):

            result = itertools.permutations(G)
            result = [list(item) for item in result]
            return result



            import math
    class Solution:

        def permute(self, G):        


            factor = math.factorial

            def findStartingIndex(num, sequence):
                edges = G[:]

                result = []
                remainder = sequence        

                while remainder>1:

                    next_max = factor(num-1)
                    div = remainder//next_max
                    remainder = remainder%next_max
                    if(remainder==0):
                        div-=1
                        remainder = next_max

                    result.append(edges[div])

                    edges.pop(div)
                    num-=1

                result.extend(edges)
                return result 

            n = factor(len(G))
            if n==1:
                return [[1]]
            ans =[]

            for i in range(1, n+1):
                ans.append(findStartingIndex(len(G), i)) 

            return ans
    """

In [48]:
#Example 
obj = Solution()
obj.permute(["one", "two", "three"])

[['one', 'two', 'three'],
 ['one', 'three', 'two'],
 ['two', 'one', 'three'],
 ['two', 'three', 'one'],
 ['three', 'one', 'two'],
 ['three', 'two', 'one']]

---

In [49]:
# Adjacency list representation of a graph in python 
graph = { "a" : ["c"],
          "b" : ["c", "e"],
          "c" : ["a", "b", "d", "e"],
          "d" : ["c"],
          "e" : ["c", "b"],
          "f" : []
        }

In [50]:
# Print all edges of the graph given above
def generate_edges(graph):
    edges = []
    for node in graph:
        for neighbour in graph[node]:
            edges.append((node, neighbour))

    return edges
generate_edges(graph)

[('a', 'c'),
 ('b', 'c'),
 ('b', 'e'),
 ('c', 'a'),
 ('c', 'b'),
 ('c', 'd'),
 ('c', 'e'),
 ('d', 'c'),
 ('e', 'c'),
 ('e', 'b')]

In [51]:
"""
Find isolated nodes from the graph given above
"""
def findIsolatedNodes(graph):
    isolated=[]
    for node in graph:
        if(not graph[node]):
            isolated.append(node)
    
    return isolated
findIsolatedNodes(graph)        

['f']

---

In [68]:
"""Bredth First Search implementation.
"""
class Graph:
    def __init__(self, graph=None):
        if graph:
            self.g = graph
        else:
            self.g = defaultdict(list)
    
    def BFS(self, s, d):
        '''
        Finds a path between s and d.
        '''
        queue =[[s, [s]]]
        ans = []  
        while queue:
            node = queue.pop(0)   
            
            if node[0]==d:
                ans.append(node[1])
                continue
            
            for item in set(self.g[node[0]])-set(node[1]):
                queue.append([item, node[1]+[item]])
                            
        return ans
    
# Alternatively 
'''
Knowing that the shortest path will be returned first from the BFS path search method,
we can just return the path found first. 
'''
def bfs_paths_shortest(graph, start, goal):
    queue = [(start, [start])]
    ans =[]
    while queue:
        vertex, path = queue.pop(0)
        if(vertex==goal):
            return path
            
        for node in set(graph[vertex]) - set(path):
            queue.append([node, path + [node]])
    
    return ans

#Here we are using Breadth Frist Search to find all possible paths.
def bfs_paths(graph, start, goal):
    queue = [(start, [start])]
    ans =[]
    while queue:
        vertex, path = queue.pop(0)
        if(vertex==goal):
            ans.append(path)
            continue
            
        for node in set(graph[vertex]) - set(path):
            queue.append([node, path + [node]])
    
    return ans

In [74]:
"""
Similarly for Depth First Search
"""
def dfs_paths(graph, start, goal):
    stack = [(start, [start])]
    ans =[]
    while stack:
        (vertex, path) = stack.pop()
        if vertex == goal:
            ans.append(path)
            
        for node in set(graph[vertex]) - set(path):
            stack.append((node, path + [node]))
    return ans

In [70]:
#Example 
graph = {'A': ['B', 'C'],
         'B': ['A', 'D', 'E'],
         'C': ['A', 'F'],
         'D': ['B'],
         'E': ['B', 'F'],
         'F': ['C', 'E']}

In [71]:
bfs_paths(graph, 'A', 'F')

[['A', 'C', 'F'], ['A', 'B', 'E', 'F']]

In [72]:
bfs_paths_shortest(graph, 'A', 'F')

['A', 'C', 'F']

In [73]:
dfs_paths(graph, 'A', 'F')

[['A', 'B', 'E', 'F'], ['A', 'C', 'F']]

---

In [75]:
"""
Graph coloring problem

Example:
How many ways can the colors {R, G, B} assigned to the graph?

*Time complexity 3^n

1 -- 2
|    |
4 -- 3
"""
from collections import defaultdict

def colorInAdjacent(node, graph, adj_color, color):
    
    for item in graph[node]:
        if adj_color[item]==color:
            return True
        
    return False

def findAllCombinations(links, colors, source, dest, n):
    
    graph = defaultdict(list)
    
    for i, j in links:
        graph[i].append(j)
        graph[j].append(i)
        
    result = []
    adj_color = dict.fromkeys(graph.keys())
    
    def backtracking(s, d, color, temp, visited):
        
        visited = visited +[s]
        adj_color[s] = color
        
        if s==d and len(temp)==n:
            result.append(temp)
            return 
        
        for node in set(graph[s])-set(visited):
            
            for c in colors:
                if not colorInAdjacent(node, graph, adj_color, c): # bounding function!!
                    backtracking(node, d, c, temp+[c], visited)
            adj_color[node] = None
    
    for color in colors:
        backtracking(source, dest, color, [color], [])

    
    return result       

In [76]:
links = [[1, 2], [2, 3], [3, 4], [4, 1]]
color = ["R", "G", "B"]
source = 1
dest = 4
findAllCombinations(links, color, source, dest, 4)

[['R', 'G', 'R', 'G'],
 ['R', 'G', 'R', 'B'],
 ['R', 'G', 'B', 'G'],
 ['R', 'B', 'R', 'G'],
 ['R', 'B', 'R', 'B'],
 ['R', 'B', 'G', 'B'],
 ['G', 'R', 'G', 'R'],
 ['G', 'R', 'G', 'B'],
 ['G', 'R', 'B', 'R'],
 ['G', 'B', 'R', 'B'],
 ['G', 'B', 'G', 'R'],
 ['G', 'B', 'G', 'B'],
 ['B', 'R', 'G', 'R'],
 ['B', 'R', 'B', 'R'],
 ['B', 'R', 'B', 'G'],
 ['B', 'G', 'R', 'G'],
 ['B', 'G', 'B', 'R'],
 ['B', 'G', 'B', 'G']]

---

In [80]:
import sys 
import heapq

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [[0]*vertices for row in range(vertices)] 

  
    def dijkstra(self, src, dest): 

        dist = [sys.maxsize] * self.V 
        dist[src] = 0
        visited = [False] * self.V 
        pqueue = []
        heapq.heappush(pqueue, (0, src, [0]))

        while pqueue: 

            cost, node, path = heapq.heappop(pqueue)
            visited[node] = True
            
            if node==dest:
                print("cost: ", cost, "and path: ", path)
                return 

            for v in range(self.V): 
                path_len = dist[node] + self.graph[node][v]
                if self.graph[node][v] > 0 and \
                visited[v] == False and dist[v] > path_len:
                    dist[v] = path_len
                    heapq.heappush(pqueue, (path_len, v, path+[v]))
    """
    Here we are using parent dictionary for identifying path once we get to destination. 
    """                
    def dijkstra2(self, src, dest): 

            dist = [sys.maxsize] * self.V 
            dist[src] = 0
            visited = [False] * self.V 
            pqueue = []
            
            parent = dict.fromkeys(range(10))
            parent[src] =src
            
            heapq.heappush(pqueue, (0, src))
            
            prevNode =src
            while pqueue: 

                cost, node = heapq.heappop(pqueue)

                visited[node] = True


                if node==dest:
                    print("cost: ", cost)
                    path = []  
                    curr = dest
                    while curr!=src:
                        path.insert(0, curr)
                        curr = parent[curr]
                    path.insert(0, src)
                    print("Path: ", path)
                    break 

                for v in range(self.V): 
                    path_len = dist[node] + self.graph[node][v]
                    if self.graph[node][v] > 0 and \
                    visited[v] == False and dist[v] > path_len:
                        dist[v] = path_len
                        heapq.heappush(pqueue, (path_len, v))
                        parent[v] = node
                        

In [81]:
g = Graph(9) 
g.graph = [[0, 4, 0, 0, 0, 0, 0, 8, 0], 
        [4, 0, 8, 0, 0, 0, 0, 11, 0], 
        [0, 8, 0, 7, 0, 4, 0, 0, 2], 
        [0, 0, 7, 0, 9, 14, 0, 0, 0], 
        [0, 0, 0, 9, 0, 10, 0, 0, 0], 
        [0, 0, 4, 14, 10, 0, 2, 0, 0], 
        [0, 0, 0, 0, 0, 2, 0, 1, 6], 
        [8, 11, 0, 0, 0, 0, 1, 0, 7], 
        [0, 0, 2, 0, 0, 0, 6, 7, 0]]; 
import numpy as np
print(np.matrix(g.graph))

[[ 0  4  0  0  0  0  0  8  0]
 [ 4  0  8  0  0  0  0 11  0]
 [ 0  8  0  7  0  4  0  0  2]
 [ 0  0  7  0  9 14  0  0  0]
 [ 0  0  0  9  0 10  0  0  0]
 [ 0  0  4 14 10  0  2  0  0]
 [ 0  0  0  0  0  2  0  1  6]
 [ 8 11  0  0  0  0  1  0  7]
 [ 0  0  2  0  0  0  6  7  0]]


In [82]:
#Example 
g.dijkstra(0, 4)

cost:  21 and path:  [0, 7, 6, 5, 4]
