In [12]:
"""
22. Generate Parentheses
Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.

For example, given n = 3, a solution set is:

[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
] 

Time complexity: O(2^n), for every index there can be two options"{" or "}". So it can be said that the upperbound
of time complexity is O(2^n) or it has exponential time complexity.

Space Complexity: O(n) if we are using global variable to store the possible outcomes.
"""
def generateParenthesis(pairs):
    
    if(pairs<=0):
        return None
    
    result = []
    
    def helper(opened, closed, case):
        
        if len(case)== 2*pairs:
            result.append(case)
            return 
        
        if opened <pairs:
            helper (opened+1, closed, case+"(")
        
        if opened>closed:
            helper(opened, closed+1, case+")")
    
    helper(1, 0, "(")
    
    return result

In [14]:
#Example
generateParenthesis(3)

['((()))', '(()())', '(())()', '()(())', '()()()']

In [3]:
"""
Given a list of integers and a target, the function given below returns a sublist of integers adding upto the target.
"""
class Solution:
    def backtracking(self, candi, res, temp, leftover: int):
        if not candi: 
            return
        half_left = leftover / 2

        for i, n in enumerate(candi):
            if n <= half_left:  # leftover in a child branch should not be smaller than the value chosen in this
                #level, otherwise it is a revisiting
                temp.append(n)
                self.backtracking(candi[i:], res, temp, leftover - n)
                temp.pop(-1)
            elif n == leftover:
                res.append(temp + [leftover])
            
    def combinationSum(self, candidates, target: int):
        candidates.sort()
        res, temp = [], []
        self.backtracking(candidates, res, temp, target)
        return res

In [4]:
#Example 
obj = Solution()
obj.combinationSum([2, 3, 6, 7], 6)

[[2, 2, 2], [3, 3], [6]]

---

In [10]:
"""
The code given blelow implements Sidoku solver. 
"""
import numpy as np
def isPossible(grid, row, col, num):
    
    for i in range(0, 9):
        if grid[row][i]==num:
            return False
    
    for i in range(0, 9):
        if grid[i][col]==num:
            return False

    col_s = (col//3)*3
    row_s = (row//3)*3
    
    for x in range(0, 3):
        for v in range(0, 3):
            if grid[row_s+x][col_s+v]==num:
                return False
    return True

"""
Time complexity of 9x9 Sidoku solver is O(9^m), where m is the number of empty/unassigned index. 
The time complexity remains the same as the naive approach, but on average it would take much 
less than the naive approach that involves trying all possible values. 
Note that we are using the upper bound for the time complexity.  

Space complexity: O(n^2), we need to store the solution
"""

count=0
def solver(grid):
    global count
    count+=1

    for i in range(9):
        for j in range(9):
            
            if grid[i][j]==0:
                for num in range(1, 10):
                    if isPossible(grid, i, j, num):
                        grid[i][j]=num
                        solver(grid)
                        grid[i][j]=0
                return
                
                        
    print(np.matrix(grid))

In [11]:
grid = [[5, 3, 0, 0, 7, 0, 0, 0, 0], 
       [6, 0, 0, 1, 9, 5, 0, 0, 0],
       [0, 9, 8, 0, 0, 0, 0, 6, 0],
       [8, 0, 0, 0, 6, 0, 0, 0, 3],
       [4, 0, 0, 8, 0, 3, 0, 0, 1],
       [7, 0, 0, 0, 2, 0, 0, 0, 6],
       [0, 6, 0, 0, 0, 0, 2, 8, 0],
       [0, 0, 0, 4, 1, 9, 0, 0, 5],
       [0, 0, 0, 0, 8, 0, 0, 0, 0]]
solver(grid)

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


---

In [21]:
"""
Here we are using back-tracking to find sum of subsets
"""

def sumOfSubsets(arr, target):
    
    result = []
    def helper(nums, temp, reminder):

        
        for i, item in enumerate(nums):
            
            if item>reminder: # bounding condition 
                return 
            if item==reminder:
                result.append(temp+[item])
            else:
                helper(nums[i+1:], temp+[item], reminder-item)
    
    helper(arr, [], target)
    return result             

In [22]:
sumOfSubsets([5, 10, 12, 13, 15, 18], 30)

[[5, 10, 15], [5, 12, 13], [12, 18]]